
development:
  adapter: postgresql
  encoding: unicode
  database: demo_app_development
  pool: 5
  username: riverbryant
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: demo_app_test
  pool: 5
  username: riverbryant
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: demo_app_production
  pool: 5
  username: riverbryant
  password:
